ALTER TABLE "Project" ALTER COLUMN "budgetLimit" TYPE DECIMAL(65,30);
ALTER TABLE "Budget" ALTER COLUMN "limit" TYPE DECIMAL(65,30), ALTER COLUMN "spent" TYPE DECIMAL(65,30);
ALTER TABLE "Expense" ALTER COLUMN "amount" TYPE DECIMAL(65,30);
ALTER TABLE "RecurringExpense" ALTER COLUMN "amount" TYPE DECIMAL(65,30);
